### ISSUE TITLE
FormatNumericToString - isNegative first value clarification

### ISSUE THREAD

**Issue by ilteoood** [tc39/proposal-intl-numberformat-v3#109]
Hi guys,
I'm looking at the [FormatNumericToString](https://tc39.es/proposal-intl-numberformat-v3/out/numberformat/diff.html#sec-formatnumberstring) function, and I'm here to ask why in line `1a` we set `isNegativeValue` to true.

At line `3` we are going to replace it anyway.
IMO we should avoid the check on line `3` if x is negative-zero and also we could move the assert on line `2` as first action.

What do you think about it?

cc: @micheleriva

**Comment by sffc** [comment]
Yes, good catch 👍

**Comment by sffc** [comment]
Duplicate of https://github.com/tc39/proposal-intl-numberformat-v3/issues/67
