### ISSUE TITLE
Improve GetStringOrBooleanOption

### ISSUE THREAD

**Issue by FrankYFTang** [tc39/proposal-intl-numberformat-v3#20]
Currently, https://tc39.es/proposal-intl-numberformat-v3/out/negotiation/diff.html#sec-getoption
(notice the section ID should be changed from #sec-getoption to #sec-getstringorbooleanoption  for GetStringOrBooleanOption instead of the one for the GetOption)
have

1.2.12 GetStringOrBooleanOption ( options, property, values, trueValue, fallback )
The abstract operation GetStringOrBooleanOption extracts the value of the property named 
property from the provided options object. If the value is undefined, the operation returns 
fallback. If the value is true, the operation returns trueValue. If the value is falsy, 
the operation returns false. Otherwise, the operation converts the value to a String, 
checks whether it is one of a List of allowed values (which must not be undefined), 
and returns the stringified value.

1. Let value be ? Get(options, property).
2. If value is undefined, then return fallback.
3. If value is true, then return trueValue.
4. Let valueBoolean be ToBoolean(value).
5. If valueBoolean is false, then return valueBoolean.
6. Let value be ? ToString(value).
7. If values does not contain an element equal to value, throw a RangeError exception.
8. Return value.

I suggest we change it to the following to make it more generalized:

1.2.12 GetStringOrBooleanOption ( options, property, values, **^falseValue,^** trueValue, fallback )
The abstract operation GetStringOrBooleanOption extracts the value of the property named 
property from the provided options object. If the value is undefined, the operation returns 
fallback. If the value is true, the operation returns trueValue. If the value is false, 
the operation returns **^falseValue^**. Otherwise, the operation converts the value to a String, 
checks whether it is one of a List of allowed values (which must not be undefined), 
and returns the stringified value.

1. Let value be ? Get(options, property).
2. If value is undefined, then return fallback.
3. If value is true, then return trueValue.
4. If value is false, then return **^falseValue^**.
5. Let value be ? ToString(value).
6. If values does not contain an element equal to value, throw a RangeError exception.
7. Return value.

@sffc

**Comment by sffc** [comment]
@FrankYFTang LMK if my fix in 8c82d8c satisfies your suggestion.
