### ISSUE TITLE
Take care about `Number.prototype.toFixed`

### ISSUE THREAD

**Issue by aleen42** [tc39/proposal-intl-numberformat-v3#31]
Currently, `Number.prototype.toFixed` cannot specify a different rounding mode, and hope that it can be taken into consideration in this proposal since that it has brought out different kinds of rounding modes in JavaScript.

```js
(1.02).toFixed(1); // => "1.0"
(1.05).toFixed(1); // => "1.1" round by default

// If we can specify types:
(1.05).toFixed(1, 'floor'); // => "1.0"
(1.02).toFixed(1, 'ceiling'); // => "1.1"
```

**Comment by sffc** [comment]
CC @littledan 

This proposal is scoped to only Intl.NumberFormat, but there are other proposals in the works where this might be relevant.  Consider opening an issue on https://github.com/tc39/proposal-decimal.

Closing here because this is not in scope for 402.
