### ISSUE TITLE
Does undefined alias to auto include compact notation?

### ISSUE THREAD

**Issue by Blockzez** [tc39/proposal-intl-numberformat-v3#40]
Right now, this proposal specifies that `undefined` aliases to `"auto"`.
Does this also include `"compact"` notation, considering ICU defaults it to `"min2"` for compact notation so that `true` equates to `'min2"` for compact notation in the current Intl.NumberFormat?

**Comment by sffc** [comment]
Good catch!  Yes, I will change the proposal to reflect web reality, which is using `"min2"` for compact notation.
