### ISSUE TITLE
please fix the diff of SetNumberFormatDigitOptions 

### ISSUE THREAD

**Issue by FrankYFTang** [tc39/proposal-intl-numberformat-v3#43]
Please fix the diff version of 
https://tc39.es/proposal-intl-numberformat-v3/out/numberformat/diff.html#sec-initializenumberformat

The green/pink highlight looks missed a lot of changes from https://tc39.es/ecma402/ and is now very confusing to figure out which part is the change. Please compare with https://tc39.es/ecma402/ and highlight it correctly.

**Comment by sffc** [comment]
The proposal's diff is based on upstream editorial PR https://github.com/tc39/ecma402/pull/575, which is approved but not yet merged.
