### ISSUE TITLE
Typo involving trailingZeroDisplay

### ISSUE THREAD

**Issue by sffc** [tc39/proposal-intl-numberformat-v3#48]
Jeff Walden found a typo:

https://tc39.es/proposal-intl-numberformat-v3/out/numberformat/diff.html#sec-initializenumberformat step 24 should be "trailingZeroDisplay" (no initial cap)

**Comment by chicoxyzzy** [comment]
Duplicate of https://github.com/tc39/proposal-intl-numberformat-v3/issues/42
