### ISSUE TITLE
Add paragraph explicitly stating the motivation for this proposal

### ISSUE THREAD

**Issue by sffc** [tc39/proposal-intl-numberformat-v3#5]
Suggestion to add a paragraph such as the following to the README:

> In ECMA-402, we receive dozens of feature requests each year.  When forming this proposal, the author (Shane F. Carr) considered every feature request relating to Intl.NumberFormat and put them up against the following criteria:
>
> 1. The feature must have multiple stakeholders.
> 2. The feature must have robust prior art, e.g., in CLDR, ICU, or Unicode.
> 3. The feature must be difficult to implement in user land (such as a locale data dependency).
>
> All parts of this proposal meet that bar, and furthermore, the author's intent is that all Intl.NumberFormat feature requests meeting that bar are part of this proposal.

@zbraniecki SGTY?

**Comment by zbraniecki** [comment]
Yep!
