### ISSUE TITLE
Add range checks to ResolvePluralRange to match PartitionNumberRangePattern?

### ISSUE THREAD

**Issue by anba** [tc39/proposal-intl-numberformat-v3#50]
Should `ResolvePluralRange` perform the same range checks as `PartitionNumberRangePattern` (steps 1-4)?

**Comment by sffc** [comment]
`ResolvePluralRange` should check for `x < y`, but the steps don't need to be as complicated because `ResolvePluralRange` accepts a Number whereas `PartitionNumberRangePattern` accepts an Intl mathematical value.
