### ISSUE TITLE
SetNumberFormatDigitOptions uses non-ECMASpeak syntax

### ISSUE THREAD

**Issue by anba** [tc39/proposal-intl-numberformat-v3#51]
From <https://tc39.es/proposal-intl-numberformat-v3/out/numberformat/diff.html#sec-setnfdigitoptions>:

```
If ( not hasSd and notation is not "compact" ) or roundingPriority is not "auto", set needFd to true; else, set needFd to false.
```

As mentioned in the other ECMA-402 PR, we need to explicitly compare against boolean values. And also parenthesised expressions aren't ECMASpeak syntax. Two possible alternatives are either using ", or if" to separate the two conditions:

```
If hasSd is false and notation is not "compact", or if roundingPriority is not "auto", set needFd to true; else, set needFd to false.
```

Or to use separate if-clauses:
```
If hasSd is false and notation is not "compact", set needFd to true.
Else if roundingPriority is not "auto", set needFd to true.
Else, set needFd to false.
```

**Comment by sffc** [comment]
This should be resolved in tandem with #41 and tc39/ecma402#575.
