### ISSUE TITLE
PartitionNumberRangePattern return value is infallible

### ISSUE THREAD

**Issue by codehag** [tc39/proposal-intl-numberformat-v3#56]
In 

https://tc39.es/proposal-intl-numberformat-v3/out/numberformat/diff.html#sec-partitionnumberrangepattern

Line 15 should be infallible, that is: `Return ! CollapseNumberRange(result).`

**Comment by sffc** [comment]
I see.  According to https://tc39.es/ecma262/#sec-runtime-semantics:

> Algorithms which specify semantics that must be called at runtime are called runtime semantics. Runtime semantics are defined by abstract operations or syntax-directed operations. **Such algorithms always return a completion record.**

I was thinking that if a function never threw an exception, then we didn't need `!`/`?`, but actually it seems we do, since this is a runtime function!
